### ISSUE TITLE
Missing .obj file

### ISSUE THREAD

**Issue by non-void** [2iw31Zhv/AnisotropicElastoplasticity#1]
Hello, I compiled the project and found an .obj file missing used in main.cpp, can you provide it in the repo?
They are from line 77 and 78 in the main.cpp.
Thanks a lot.

`	
LagrangianMesh mesh = LagrangianMesh::ObjMesh(
		"square_hr2x06.obj", 2e3, 0.04, 200, 0.3, 0.0, 4e4, 0.0);
`

**Comment by 2iw31Zhv** [comment]
Hello non-void, I thought any .obj files representing a simple cloth should work. You could use Triangle to prepare your own (https://www.cs.cmu.edu/~quake/triangle.html).
Or, you could try this one
https://drive.google.com/open?id=1WvlVbOpLfaU_vtmcOmsBOTGBpRaPxiLq

**Comment by non-void** [comment]
Thank you, this solved my problem.
