### ISSUE TITLE
The calculation of inverseR

### ISSUE THREAD

**Issue by Linxu-Fan** [2iw31Zhv/AnisotropicElastoplasticity#3]
Hi:

Does this function "Eigen::Matrix2d inverseR(const Eigen::Matrix2d& R)" calculate the inverse of a 2x2 matrix? If yes, it seems to be wrong. Thanks.

**Comment by 2iw31Zhv** [comment]
It is not general and should work for an upper triangular matrix. Please let me know if there is any other questions, thx

**Comment by Linxu-Fan** [comment]
Thanks, that makes sense.
